Add Trivy scanning  (#46)

diff --git a/.github/workflows/build-scan-push.yml b/.github/workflows/build-scan-push.yml
--- a/.github/workflows/build-scan-push.yml
+++ b/.github/workflows/build-scan-push.yml
@@ -3,7 +3,6 @@ name: BUILD-SCAN-PUSH
 on:
   push:
     branches: [ '**' ]
-  pull_request:
   workflow_dispatch:
 
 jobs:
@@ -73,21 +72,51 @@ jobs:
             docker image tag ${{steps.setImageDetails.outputs.fullImageName}} $TAG
           done
 
-      - name: run anchore grype scan
-        id: scan
+      - name: Run Anchore Grype scan
+        id: grype-scan
         if: ${{ matrix.target == 'production' }}
-        uses: anchore/scan-action@v3
+        uses: anchore/scan-action@v6
         with:
           image: ${{steps.setImageDetails.outputs.fullImageName}}
           fail-build: true
           severity-cutoff: "medium"
+        continue-on-error: true
 
-      - name: Inspect action SARIF report
+      - name: Run Aqua Trivy scan
+        id: trivy-scan
         if: ${{ matrix.target == 'production' }}
-        run: cat ${{ steps.scan.outputs.sarif }}
+        uses: aquasecurity/trivy-action@0.30.0
+        with:
+          image-ref: ${{steps.setImageDetails.outputs.fullImageName}}
+          format: sarif
+          output: trivy-reports-dotnet-${{ matrix.image.netVersion }}
+          exit-code: 1
+          vuln-type: os,library
+          severity: CRITICAL,HIGH,MEDIUM
+        continue-on-error: true
+
+      - name: Upload Grype SARIF report
+        if: ${{ steps.grype-scan.outcome == 'failure' && matrix.target == 'production' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: grype-reports-dotnet-${{ matrix.image.netVersion }}
+          path: ${{ steps.grype-scan.outputs.sarif }}
+
+      - name: Upload Trivy SARIF report
+        if: ${{ steps.trivy-scan.outcome == 'failure' && matrix.target == 'production' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-reports-dotnet-${{ matrix.image.netVersion }}
+          path: trivy-reports-dotnet-${{ matrix.image.netVersion }}
+
+      - name: Fail build if scans failed
+        if: ${{ (steps.grype-scan.outcome == 'failure' || steps.trivy-scan.outcome == 'failure') && matrix.target == 'production' }}
+        run: |
+          echo "One or more scans failed. Failing the build."
+          exit 1
 
       - name: Login to DockerHub
-        uses: docker/login-action@v1
+        uses: docker/login-action@v2
         if: github.ref == 'refs/heads/master'
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
@@ -102,10 +131,3 @@ jobs:
           do
             docker image push $TAG
           done
-
-      - name: Upload Anchore Grype SARIF report
-        if: ${{ failure() && matrix.target == 'production' }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: anchore-reports-dotnet-${{ matrix.image.netVersion }}
-          path: ${{ steps.scan.outputs.sarif }}
