Update nightly scan

diff --git a/.github/workflows/nightly-scan.yml b/.github/workflows/nightly-scan.yml
--- a/.github/workflows/nightly-scan.yml
+++ b/.github/workflows/nightly-scan.yml
@@ -28,22 +28,43 @@ jobs:
       - uses: actions/checkout@v4
       - name: Set job environment variables
         run:  cat JOB.env >> $GITHUB_ENV
-
-      - name: Scan .NET docker image
-        id: scan
-        uses: anchore/scan-action@v3
+      - name: Run Anchore Grype scan
+        id: grype-scan
+        uses: anchore/scan-action@v6
         with:
           image: defradigital/${{env.IMAGE_NAME}}:${{env.DEFRA_VERSION}}-dotnet${{matrix.image.netVersion}}
           fail-build: true
           severity-cutoff: "medium"
+        continue-on-error: true
 
-      - name: Inspect action SARIF report
-        if: ${{ failure() }}
-        run: cat ${{ steps.scan.outputs.sarif }}
+      - name: Run Aqua Trivy scan
+        id: trivy-scan
+        uses: aquasecurity/trivy-action@0.30.0
+        with:
+          image-ref: defradigital/${{env.IMAGE_NAME}}:${{env.DEFRA_VERSION}}-dotnet${{matrix.image.netVersion}}
+          format: sarif
+          output: 'trivy-scan.sarif'
+          exit-code: 1
+          vuln-type: os,library
+          severity: CRITICAL,HIGH,MEDIUM
+        continue-on-error: true
 
-      - name: Upload Anchore Grype SARIF report
-        if: ${{ failure() }}
+      - name: Upload Grype SARIF report
+        if: ${{ steps.grype-scan.outcome == 'failure' }}
         uses: actions/upload-artifact@v4
         with:
-          name: anchore-reports-dotnet-${{ matrix.image.netVersion }}
-          path: ${{ steps.scan.outputs.sarif }}
+          name: grype-reports-dotnet-${{ matrix.image.netVersion }}
+          path: ${{ steps.grype-scan.outputs.sarif }}
+
+      - name: Upload Trivy SARIF report
+        if: ${{ steps.trivy-scan.outcome == 'failure' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-reports-dotnet-${{ matrix.image.netVersion }}
+          path: trivy-scan.sarif
+
+      - name: Fail build if scans failed
+        if: ${{ (steps.grype-scan.outcome == 'failure' || steps.trivy-scan.outcome == 'failure') }}
+        run: |
+          echo "One or more scans failed. Failing the build."
+          exit 1
